### PR TITLE
add gemetry validations and test cases

### PR DESCRIPTION
**Pull request by YeWintNaing05**

### CODE REVIEW

**Comment by vincent-paing** [comment]
Can you clarify which validations are added?

**Comment by YeWintNaing05** [comment]
validation for seven geometry types according to GeoJSON Specification (RFC 7946)

**Comment by vincent-paing** [comment]
Ah, I see you closed the PR. Sorry, I've been quite busy and couldn't check the files, I think there was some problems with indentation in the files it created a lot of diffs. I will add a contribution guide when I'm free and add the codestyle inside the repo so that that can be prevented later

**Comment by YeWintNaing05** [comment]
Sorry bro,I close the PR because of the many conflict (indentation coz of
me(I did format the code ) and I would like to fix conflict  and also
validation style  .After all, I will resend the PR again. Thanks you for
your reply.

**Pull request closed without merging**
